"use client";
import { useMemo, useState } from "react";
import { Volume2 } from "lucide-react";
import { speak } from "@/lib/speech";
import { allWords } from "@/data/lessons";
import { useProgress } from "./ProgressProvider";
const quizWords = [allWords[0], allWords[1], allWords[3], allWords[8], allWords[10], allWords[11], allWords[13], allWords[17], allWords[48], allWords[49], allWords[50], allWords[51]];
export function ChoiceGame({ mode }: { mode: "listen" | "look" }) { const { answerQuiz } = useProgress(); const [round, setRound] = useState(0); const [feedback, setFeedback] = useState<"correct" | "wrong" | null>(null); const choices = useMemo(() => quizWords.slice(round % 6, round % 6 + 4), [round]); const answer = choices[0]; const shuffled = useMemo(() => [...choices].sort((a,b) => a.word.localeCompare(b.word)), [choices]); const choose = (word: string) => { if (feedback === "correct") return; const correct = word === answer.word; answerQuiz(correct); setFeedback(correct ? "correct" : "wrong"); if (correct) setTimeout(() => { setRound((v) => (v + 1) % 6); setFeedback(null); }, 1100); }; return <section className={`game-card ${feedback === "correct" ? "celebrating" : ""}`}><div className="round-indicator" aria-label={`Question ${round + 1} of 6`}>{[0,1,2,3,4,5].map((step) => <span key={step} className={step === round ? "current" : step < round ? "passed" : ""}/>)}</div><div className="game-label">{mode === "listen" ? "Listen & Choose" : "Look & Choose"}</div>{mode === "listen" ? <button className="sound-orb" onClick={() => speak(answer.word)} aria-label="Play word"><Volume2 size={42}/><span>Tap to listen</span></button> : <><div className="quiz-emoji" role="img" aria-label="mystery word">{answer.emoji}</div><h2>What is this?</h2></>}<div className={`answer-grid ${mode === "listen" ? "emoji-answers" : ""}`}>{shuffled.map((choice) => <button key={choice.word} onClick={() => choose(choice.word)} className={feedback === "correct" && choice.word === answer.word ? "correct" : ""}>{mode === "listen" ? <><span>{choice.emoji}</span><small>{choice.word}</small></> : choice.word}</button>)}</div><div className={`feedback ${feedback ?? ""}`} role="status">{feedback === "correct" ? <>🎉 Great Job! <b>+2 ⭐</b></> : feedback === "wrong" ? <>Almost! Try again 😊</> : <>Choose an answer!</>}</div></section>; }
const matchItems = [allWords[0], allWords[10], allWords[48]];
export function MatchGame() { const { answerQuiz, completeQuiz } = useProgress(); const [left, setLeft] = useState<string | null>(null); const [matched, setMatched] = useState<string[]>([]); const [message, setMessage] = useState("Match each picture with its word!"); const chooseWord = (word: string) => { if (!left) { setMessage("Choose a picture first 👆"); return; } const good = left === word; answerQuiz(good); if (good) { const next = [...matched, word]; setMatched(next); setMessage("Great match! +2 ⭐"); setLeft(null); if (next.length === matchItems.length) { completeQuiz(); setMessage("Quiz complete! +10 ⭐ 🎉"); } } else setMessage("Almost! Try another word 😊"); }; return <section className="game-card"><div className="game-label">Match</div><h2>Make the pairs!</h2><div className="match-board"><div>{matchItems.map((item) => <button key={item.word} disabled={matched.includes(item.word)} className={left === item.word ? "selected" : ""} onClick={() => setLeft(item.word)}>{item.emoji}</button>)}</div><div>{[matchItems[2],matchItems[0],matchItems[1]].map((item) => <button key={item.word} disabled={matched.includes(item.word)} onClick={() => chooseWord(item.word)}>{item.word}</button>)}</div></div><p className="match-message" role="status">{message}</p>{matched.length === matchItems.length && <button className="soft-button" onClick={() => { setMatched([]); setMessage("Match each picture with its word!"); }}>Play Again</button>}</section>; }
